### ISSUE TITLE
掌上理工大有使用这个库吗？

### ISSUE THREAD

**Issue by XiongCaixing** [cx478815108/JSONRenderKit#1]
我下载了掌上理工大iOS版本，发现没有使用该库啊？是不是有审核问题

**Comment by cx478815108** [comment]
你好喔，非常高兴收到你的邮件我开发了一个更好的库，这个库已经被取代啦。你可以到我的主页查看 TokenHybrid 这个项目
还有问题，欢迎随时联系我
来自阿里邮箱 iPhone版 ------------------原始邮件 ------------------发件人：XiongCaixing <notifications@github.com>日期：2018-05-06 17:02:05收件人：cx478815108/JSONRenderKit <JSONRenderKit@noreply.github.com>抄送：Subscribed <subscribed@noreply.github.com>主题：[cx478815108/JSONRenderKit] 掌上理工大有使用这个库吗？ (#1)我下载了掌上理工大iOS版本，发现没有使用该库啊？是不是有审核问题

**Comment by XiongCaixing** [comment]
thanks
